#!/bin/bash

if [ ${#} == 0 ]; then
    cat <<EOF
No file given to export.
        Usage: $(basename "$0") <file.tikz>

EOF
    exit 1
fi

for file in "$@"; do
    base="${file%\.*}"
    tikz2pdf "$file" && pdf2svg "$base".pdf "$base".svg
done
