#!/bin/bash

png_density="1200";
png_size="600";

if [ ${#} == 0 ]; then
    cat <<EOF
No file given to export.
        Usage: $(basename "$0") <file.tikz>

EOF
    exit 1
fi

verbose=false
if [ "$1" == "-v" ]; then
    verbose=true
    shift
fi

for file in "$@"; do
  $verbose && echo "Converting $file..."
  base="${file%\.*}"
  tikz2pdf "$file" \
    && pdftoppm -png -r $png_density -scale-to $png_size "$base".pdf "$base" \
    && mv "$base"-1.png "$base".png
done
