#!/bin/bash

if [ ${#} == 0 ]; then
    cat <<EOF
No file given to export.
        Usage: $(basename "$0") <file.tikz>

EOF
    exit 1
fi

tmp="/tmp/tikz2pdf-$(date "+%Y%m%d%H%M%S")";
[ -d "$tmp" ] || mkdir "$tmp"

verbose=false
if [ "$1" == "-v" ]; then
    verbose=true
    shift
fi

for file in "$@"; do
    if ! [ -f "$file" ]; then
        echo "$file does not exist; skipping..."
        continue
    fi

    $verbose && echo "Converting $file..."
    base=$(basename "${file%\.*}")
    tmpbase="$tmp"/"$base"
    texfile="$tmpbase".tex

    cat <<EOF > "$texfile"
\documentclass[tikz]{standalone}
\usepackage{graphicx}
\usepackage{pgfplots}
\pgfplotsset{compat=1.16}
\begin{document}
\input{$file}
\end{document}
EOF

    pdflatex -interaction=nonstopmode -output-directory="$tmp" "$texfile" > "$tmp"/tikz2pdf.log \
        && mv "$tmpbase".pdf "${file%\.*}".pdf
done
