#!/bin/bash

if [ ${#} == 0 ]; then
    cat <<EOF
No file given to export.
        Usage: $(basename "$0") <file.tikz>

EOF
    exit 1
fi

verbose=false
if [ "$1" == "-v" ]; then
    verbose=true
    shift
fi

for file in "$@"; do
    base="${file%\.*}"
    $verbose && echo "Converting $file..."
    tikz2pdf "$file" && pdf2svg "$base".pdf "$base".svg
done
